### ISSUE TITLE
При подключении JS-скриптов без src не нужно указывать атрибут defer

### ISSUE THREAD

**Issue by Ronef** [DivanDesign/MODXEvo.snippet.ddYMap#2]
W3C-валидатор показывает ошибку:
![image](https://user-images.githubusercontent.com/1333424/54285599-550eb300-45b3-11e9-9f76-4fdfce0fc141.png)

Пофиксить здесь:
![image](https://user-images.githubusercontent.com/1333424/54285625-648dfc00-45b3-11e9-8155-57c1e9295201.png)

**Comment by Tornek** [comment]
@Ronef да мало ли что он там показывает. этот атрибут позволяет быстрее отображать пользователю данные так как выполнения скрипта не блокирует загрузку контента.

вот [список ]( https://caniuse.com/#search=defer)поддерживаемости у браузеров
вот [описание ](https://www.w3schools.com/TAGS/att_script_defer.asp) на сайте w3c.
